# Generated by Django 3.2.8 on 2021-12-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0003_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mailId',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
