# Generated by Django 3.2.8 on 2021-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0004_student_mailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tenthBoard',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tenthPercent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tenthSchool',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfthPercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfthSchool',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='twelveboard',
            field=models.CharField(default='', max_length=100),
        ),
    ]
