# Generated by Django 3.2.8 on 2021-12-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0005_auto_20211224_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='twelveboard',
            new_name='twelveBoard',
        ),
    ]
