# Generated by Django 3.2.8 on 2021-12-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0006_rename_twelveboard_student_twelveboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='twelfthPercent',
            new_name='twelvePercent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='twelfthSchool',
            new_name='twelveSchool',
        ),
    ]
